# See http://travis-ci.org/encukou/pytmxlib

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - python setup.py develop
  - '[ "$USE_LXML" = "yes" ] && pip install --use-mirrors lxml; :'
  - '[ "$USE_PIL" = "yes" ] && pip install --use-mirrors pillow; :'
  - pip install pytest-cov --use-mirrors
  - pip install coveralls --use-mirrors
env:
  - USE_LXML=no  USE_PIL=no  PYTMXLIB_TEST_SKIP_IMAGE=yes
  - USE_LXML=yes USE_PIL=no  PYTMXLIB_TEST_SKIP_IMAGE=yes
  - USE_LXML=yes USE_PIL=yes PYTMXLIB_TEST_COVERALLS=yes
script:
  - py.test -v
after_success:
  - '[ "$PYTMXLIB_TEST_COVERALLS" = "yes" ] && coveralls'
